name=EdulcoWaterSmart
version=1.0.0
author=Fabiano
maintainer=Fabiano
sentence=Arduino library for ESP32 smart water devices.
paragraph=Wi-Fi, HTTP API, relay control and modular hardware support for Edulco smart water devices.
category=Communication
url=https://github.com/fabianodaq/EdulcoWaterSmart
architectures=esp32
