#ifndef WSER_WIFI_SENTINEL_H
#define WSER_WIFI_SENTINEL_H

//-------------------------sentinel messages-------------------------
const char MSG_ALARM_SENTINEL_TEMPLATE[] PROGMEM =
"Current sensor value is outside the configured limits.\n\n"
"📏 Measured value: {VALUE} {UNIT}\n"
"👇 Minimum limit: {MIN} {UNIT}\n"
"👆 Maximum limit: {MAX} {UNIT}\n"
"⚠️ Warning time: {PERS} minutes\n\n"
"🚨 Next notification will be sent in {OCC} minutes if the alarm condition persists.\n\n"
"When the value returns within the acceptable range, a '✅ Alarm Resolved' notification will be sent automatically.\n\n"
"---\n"
"This message was automatically generated by the EdulcoWater monitoring system.";

const char MSG_RESOLVED_SENTINEL_TEMPLATE[] PROGMEM =
"✅ Alarm resolved. Current value is back within the configured limits.\n\n"
"📏 Measured value: {VALUE} {UNIT}\n"
"👇 Minimum limit: {MIN} {UNIT}\n"
"👆 Maximum limit: {MAX} {UNIT}\n"

"---\n"
"This message was automatically generated by the EdulcoWater monitoring system.";
//-------------------------sentinel messages-------------------------


// ===== Public page function =====

extern void WSER_InitSentinelSection();
extern void WSER_SentinelLoop();

extern void WSER_WiFiSentinelPage();

extern void WSER_handleSentinelGetStatus();

extern void WSER_handleSetSentinel();

extern bool WSER_ExtCmdSetSentinel(uint8_t control, bool active, int16_t minV, int16_t maxV, uint16_t pers, uint16_t occ);


#endif 
