#ifndef WSER_REPORTER_H
#define WSER_REPORTER_H

//-------------------------Reporter messages-------------------------
const char MSG_TEMPLATE_REPORTER[] PROGMEM =
"📈 EdulcoWater Reporter n° {NUM}, {TYPE} \n\n"
"---\n"
"This message was automatically generated by the EdulcoWater monitoring system.";

// ===== Public page functions =====
// Init & Loop
extern void WSER_InitReporterSection();
extern void WSER_ReporterLoop();

// Web Page sender (chunked)
extern void WSER_WiFiReporterPage();

// GET handler
extern void WSER_handleReporterGetStatus();

// POST handler
extern void WSER_handleSetReporter();

// ===== Smart Home commands (stub) =====
extern bool WSER_ExtCmdSetReporter(uint8_t ctrl, bool active, uint8_t period);
extern String WSER_ExtCmdReporterGetStatus(uint8_t ctrl);

#endif // APP_WEBBROWSER_REPORTER_H
